name = "MetaCommunityMetrics"
uuid = "3ccb93f7-bd98-4150-a201-b30c241572df"
authors = ["Yan Yin Jenny Cheung <yanyinjennycheung@gmail.com>", "Laura Melissa Guzman <guzmanur@usc.edu>"]
version = "0.1.5"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GaussianRandomFields = "e4b2fa32-6e09-5554-b718-106ed5adafe9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10"                   
Clustering = "0.15"             
Combinatorics = "1.0"           
DataFrames = "0.11.7"           
DataStructures = "0.9.0"        
Distances = "0.7.0"             
Distributions = "0.16.0"        
Documenter = "1.6"              
GaussianRandomFields = "2.0"    
Pipe = "1.3"                    
Plots = "1.40"                  
ProgressMeter = "1.0"           
SortingAlgorithms = "1.1"       
SpecialFunctions = "1.0"        
Statistics = "1"                      
julia = "1.6"                   
StatsBase = "0.24.0"            

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
