name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version: ['1.10', '1']
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
        include:
          - dataframes-version: '1.0'
            distributions-version: '0.25.111'
            statsbase-version: '0.34.3'
          - dataframes-version: '1.6'
            distributions-version: '0.25'
            statsbase-version: '0.34.3'
          - dataframes-version: '1.6'
            distributions-version: '0.25.111'
            statsbase-version: '0.33'
          - dataframes-version: '1.6'
            distributions-version: '0.25.111'
            statsbase-version: '0.34.3'
        exclude:
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: x64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v2
        with:
          key: ${{ runner.os }}-julia-${{ matrix.version }}-${{ hashFiles('Project.toml', 'Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ matrix.version }}-

      - name: Install dependencies
        run: |
          julia -e 'import Pkg; Pkg.instantiate(); \
            Pkg.add(Pkg.PackageSpec(name="DataFrames", version="${{ matrix.dataframes-version }}")); \
            Pkg.add(Pkg.PackageSpec(name="Distributions", version="${{ matrix.distributions-version }}")); \
            Pkg.add(Pkg.PackageSpec(name="StatsBase", version="${{ matrix.statsbase-version }}")); \
            Pkg.add("Coverage")'

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: true

      - name: Test loading sample data
        run: julia --project=. -e 'using MetaCommunityMetrics; df = load_sample_data(); println(df)'

      - name: Generate LCOV Report
        run: julia -e 'using Coverage; cov = process_folder("test"); LCOV.writefile("lcov.info", cov)'

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
          fail_ci_if_error: true