name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'

jobs:
  Documenter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure the entire history is available

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'  # Specify your Julia version here

      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.CRALIBE_TOKEN_1 }}
        run: julia --project=docs/ docs/make.jl
