# .github/workflows/documentation.yml
name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Install dependencies
      run: |
        julia --project=docs/ -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.add("Documenter")
          Pkg.instantiate()'

    - name: Build documentation
      run: julia --project=docs/ docs/make.jl

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build