name: TagBot

on:
  push:
    branches:
      - main  # Change to the default branch of your repository if it's not 'main'

jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - name: TagBot
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
